INSERT INTO aac_symbols(asset_name, category, canonical_text, default_tts_text, color_hex, emergency) VALUES
('ic_emergency_help','긴급어','도와주세요','도와주세요','#FF8587',TRUE),
('ic_emergency_pain','긴급어','아파요','아파요','#FF8587',TRUE),
('ic_emergency_home','긴급어','집에 갈래요','집에 가고 싶어요','#FF8587',TRUE),
('ic_emergency_hug','긴급어','안아주세요','안아주세요','#FF8587',TRUE),
('ic_emergency_scared','긴급어','무서워요','무서워요','#FF8587',TRUE),
('ic_emergency_stop','긴급어','멈춰요','멈춰주세요','#FF8587',TRUE),
('ic_person_mom','사람','엄마','엄마','#FFB185',FALSE),
('ic_person_dad','사람','아빠','아빠','#FFB185',FALSE),
('ic_person_grandma','사람','할머니','할머니','#FFB185',FALSE),
('ic_person_grandpa','사람','할아버지','할아버지','#FFB185',FALSE),
('ic_person_sibling','사람','동생','동생','#FFB185',FALSE),
('ic_person_teacher','사람','선생님','선생님','#FFB185',FALSE),
('ic_person_friend','사람','친구','친구','#FFB185',FALSE),
('ic_person_doctor','사람','의사','의사 선생님','#FFB185',FALSE),
('ic_person_driver','사람','기사님','기사님','#FFB185',FALSE),
('ic_person_police','사람','경찰관','경찰관','#FFB185',FALSE),
('ic_person_me','사람','나','나','#FFB185',FALSE),
('ic_person_we','사람','우리','우리','#FFB185',FALSE),
('ic_food_water','음식','물','물','#FFDE85',FALSE),
('ic_food_milk','음식','우유','우유','#FFDE85',FALSE),
('ic_food_juice','음식','주스','주스','#FFDE85',FALSE),
('ic_food_rice','음식','밥','밥','#FFDE85',FALSE),
('ic_food_soup','음식','국','국','#FFDE85',FALSE),
('ic_food_bread','음식','빵','빵','#FFDE85',FALSE),
('ic_food_snack','음식','과자','과자','#FFDE85',FALSE),
('ic_food_meat','음식','고기','고기','#FFDE85',FALSE),
('ic_food_egg','음식','계란','계란','#FFDE85',FALSE),
('ic_food_ramen','음식','라면','라면','#FFDE85',FALSE),
('ic_food_pizza','음식','피자','피자','#FFDE85',FALSE),
('ic_food_chicken','음식','치킨','치킨','#FFDE85',FALSE),
('ic_food_icecream','음식','아이스크림','아이스크림','#FFDE85',FALSE),
('ic_place_home','장소','집','집','#FFDE85',FALSE),
('ic_place_school','장소','학교','학교','#FFDE85',FALSE),
('ic_place_classroom','장소','교실','교실','#FFDE85',FALSE),
('ic_place_toilet','장소','화장실','화장실','#FFDE85',FALSE),
('ic_place_hospital','장소','병원','병원','#FFDE85',FALSE),
('ic_place_park','장소','공원','공원','#FFDE85',FALSE),
('ic_place_playground','장소','놀이터','놀이터','#FFDE85',FALSE),
('ic_body_head','신체','머리','머리','#FFDE85',FALSE),
('ic_body_eye','신체','눈','눈','#FFDE85',FALSE),
('ic_body_mouth','신체','입','입','#FFDE85',FALSE),
('ic_body_stomach','신체','배','배','#FFDE85',FALSE),
('ic_body_hand','신체','손','손','#FFDE85',FALSE),
('ic_body_leg','신체','다리','다리','#FFDE85',FALSE),
('ic_action_give','행동','주세요','주세요','#93F1CD',FALSE),
('ic_action_want','행동','하고 싶어요','하고 싶어요','#93F1CD',FALSE),
('ic_action_eat','행동','먹다','먹고 싶어요','#93F1CD',FALSE),
('ic_action_drink','행동','마시다','마시고 싶어요','#93F1CD',FALSE),
('ic_action_go','행동','가다','가고 싶어요','#93F1CD',FALSE),
('ic_action_come','행동','오다','오고 싶어요','#93F1CD',FALSE),
('ic_action_play','행동','놀다','놀고 싶어요','#93F1CD',FALSE),
('ic_action_sleep','행동','자다','자고 싶어요','#93F1CD',FALSE),
('ic_action_wash','행동','씻다','씻고 싶어요','#93F1CD',FALSE),
('ic_action_see','행동','보다','보고 싶어요','#93F1CD',FALSE),
('ic_emotion_good','감정','좋아요','좋아요','#93DDF1',FALSE),
('ic_emotion_dislike','감정','싫어요','싫어요','#93DDF1',FALSE),
('ic_emotion_sad','감정','슬퍼요','슬퍼요','#93DDF1',FALSE),
('ic_emotion_happy','감정','기뻐요','기뻐요','#93DDF1',FALSE),
('ic_emotion_angry','감정','화나요','화나요','#93DDF1',FALSE),
('ic_emotion_annoyed','감정','짜증나요','짜증나요','#93DDF1',FALSE),
('ic_desc_hot','설명','덥다','더워요','#93DDF1',FALSE),
('ic_desc_cold','설명','춥다','추워요','#93DDF1',FALSE),
('ic_desc_more','설명','더','더','#93DDF1',FALSE),
('ic_desc_lot','설명','많이','많이','#93DDF1',FALSE),
('ic_desc_little','설명','조금','조금','#93DDF1',FALSE),
('ic_chat_yes','대화','응','응','#8593FF',FALSE),
('ic_chat_no','대화','아니','아니','#8593FF',FALSE),
('ic_chat_wait','대화','잠깐만요','잠깐만요','#8593FF',FALSE),
('ic_chat_unknown','대화','몰라요','몰라요','#8593FF',FALSE),
('ic_chat_hello','대화','안녕','안녕','#8593FF',FALSE),
('ic_chat_thanks','대화','감사해요','감사해요','#8593FF',FALSE),
('ic_grammar_and','문법','그리고','그리고','#BDC7C1',FALSE),
('ic_grammar_but','문법','하지만','하지만','#BDC7C1',FALSE)
ON CONFLICT (asset_name) DO NOTHING;
